environment:
  VENV: "%APPVEYOR_BUILD_FOLDER%\\venv"

  matrix:
    - TOXENV: py36
      PYTHON: "C:\\Python36-x64"
      BUILD_WHEEL: 1

init:
  - echo "TOXENV- %TOXENV%"

install:
  - virtualenv -p "%PYTHON%\\python.exe" "%VENV%"
  - "%VENV%\\Scripts\\activate"
  - pip install .
  - ps: Update-AppveyorBuild -Version "v$(python -c 'import sys; import gitignoreio; sys.stdout.write(gitignoreio.__version__)') b$Env:APPVEYOR_BUILD_NUMBER"

build_script:
  - if defined BUILD_WHEEL python setup.py bdist_wheel --universal

artifacts:
  - path: "dist\\*.whl"
